name: weight_tracker
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  chart_sparkline:
  mobx: 
  flutter_mobx: 
  provider:
  google_fonts:
  lottie:
  intl:
  get_it:
  flutter_local_notifications:
  timezone:
  flutter:
    sdk: flutter

  cupertino_icons: 
  path_provider: 
  isar: 
  isar_flutter_libs: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  build_runner: 
  isar_generator: 

flutter:

  uses-material-design: true

  assets:
    - assets/
